services:
  postgres:
    image: postgres:16-alpine
    container_name: teapp-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teapp-network

  backend:
    build: .
    container_name: teapp-backend
    restart: always
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - teapp-network

volumes:
  postgres_data:

networks:
  teapp-network:
    driver: bridge
